name: Docs – Changelog on Sync Merge

on:
  pull_request_target:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: changelog-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  append:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'docs(sync):')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Ensure CHANGELOG file exists
        run: |
          mkdir -p docs
          if [ ! -f docs/CHANGELOG.md ]; then
            cat > docs/CHANGELOG.md <<'MD'
# Changelog

Список автоматических синков документации из FE/BE репозиториев.
Формат: `YYYY-MM-DD HH:MM UTC — <title> — by @actor — #PR (merge: <sha>)`
MD
          fi

      - name: Append entry
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_HTML_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          MERGE_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        run: |
          ts="$(date -u +'%Y-%m-%d %H:%M UTC')"
          short_sha="$(echo "${MERGE_SHA:-}" | cut -c1-7)"
          echo "- ${ts} — ${PR_TITLE} — by @${PR_USER} — [#${PR_NUMBER}](${PR_HTML_URL}) (merge: \`${short_sha}\`)" >> docs/CHANGELOG.md
          echo "Appended:"
          tail -n 1 docs/CHANGELOG.md

      - name: Commit & push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/CHANGELOG.md
          git commit -m "docs(changelog): append entry for sync PR #${{ github.event.pull_request.number }}"
          git push
