name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: echo ok
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo ok
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check docs
        run: echo ok
