name: Docs - Refresh Wheels
on:
  workflow_dispatch:
    inputs:
      python:
        description: "Python version"
        required: false
        default: "3.11"
  schedule:
    - cron: "0 6 * * 1"   # каждый понедельник 06:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python || '3.11' }}

      - name: Upgrade pip tooling
        run: python -m pip install -U pip pip-tools wheel

      - name: Ensure inputs/dirs
        run: |
          test -f docs/requirements.in || { echo "::error file=docs/requirements.in::Missing docs/requirements.in"; exit 2; }
          mkdir -p docs/vendor/wheels

      - name: Compile lockfile (with hashes)
        run: |
          python -m piptools compile \
            --resolver=backtracking \
            --generate-hashes \
            --allow-unsafe \
            -o docs/requirements.lock.txt docs/requirements.in
          sed -n '1,120p' docs/requirements.lock.txt

      - name: Download wheels (prefer wheels; fallback to sdist)
        run: |
          set -euxo pipefail
          python -m pip download --only-binary=:all: --require-hashes \
            -r docs/requirements.lock.txt -d docs/vendor/wheels || \
          python -m pip download -r docs/requirements.lock.txt -d docs/vendor/wheels
          ls -1 docs/vendor/wheels | head -n 80

      - name: Offline sanity build (no heredoc)
        run: |
          set -euxo pipefail
          python -m venv .venv
          . .venv/bin/activate
          pip install --no-index --find-links=docs/vendor/wheels -r docs/requirements.lock.txt
          mkdir -p docs/import
          [ -f docs/import/index.md ] || printf '# Import (autogen)\n\nPlaceholder; will be replaced by sync.\n' > docs/import/index.md
          python -m mkdocs build --strict

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "ci/docs-refresh-wheels"
          branch-suffix: timestamp
          add-paths: |
            docs/requirements.lock.txt
            docs/vendor/wheels/**
          signoff: true
          title: "Docs: refresh wheelhouse & lock (offline PyPI)"
          commit-message: |
            docs(ci): refresh wheelhouse & lock (offline)
          body: |
            - Updated lockfile (pip-tools with hashes)
            - Downloaded wheels to docs/vendor/wheels
            - Verified offline mkdocs build (--strict)
