name: Docs - Preview

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-preview.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "mkdocs-git-revision-date-localized-plugin==1.2.0"

      - name: Diagnostics
        run: |
          python - <<'PY'
          import importlib.util
          ok = importlib.util.find_spec("mkdocs_git_revision_date_localized") is not None
          import subprocess, sys
          print("plugin_present:", ok)
          subprocess.run(["mkdocs", "--version"], check=True)
          PY

      - run: mkdocs build --strict
