concurrency:
  group: docs-sync
  cancel-in-progress: true

name: Docs – Auto Merge Sync PRs
on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
permissions:
  pull-requests: write
  contents: write
jobs:
  guard-and-merge:
    # Запускаем только для PR с меткой automerge
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable PR auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          # GITHUB_TOKEN уже имеет нужные скоупы под указанными permissions
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
      - name: Cleanup stale sync artifacts
        run: scripts/cleanup_sync.sh tqlismqn/gtrack-docs
