name: docs-auto-merge-sync

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled, ready_for_review, edited, review_requested]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: automerge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  enable-and-merge:
    name: Enable auto-merge for sync PRs (CLI)
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "PR=${{ github.event.pull_request.number }}"
          echo "ref=${{ github.event.pull_request.head.ref }}"
          echo "title=${{ github.event.pull_request.title }}"
          echo "author=${{ github.event.pull_request.user.login }}"
          echo "labels=${{ join(github.event.pull_request.labels.*.name, ',') }}"

      - name: Collect changed files
        id: files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          gh api "repos/${{ github.repository }}/pulls/$PR/files" --paginate --jq '.[].filename' > files.txt
          echo "Changed files:"; cat files.txt || true
          if [ ! -s files.txt ]; then
            echo "::notice::No changed files listed. Skipping auto-merge."
            echo "in_import=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          BAD=$(grep -v '^docs/import/' files.txt || true)
          if [ -n "$BAD" ]; then
            echo "::notice::PR touches outside docs/import/**. Skipping auto-merge."
            echo "in_import=false" >> $GITHUB_OUTPUT
          else
            echo "in_import=true" >> $GITHUB_OUTPUT
          fi

      - name: Decide trust
        id: trust
        run: |
          REF="${{ github.event.pull_request.head.ref }}"
          TITLE="${{ github.event.pull_request.title }}"
          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          TRUSTED=false
          if [[ "$REF" == *sync* || "$LABELS" == *sync* || "$TITLE" == *"docs(sync)"* || "$AUTHOR" == "tqlismqn" || "$AUTHOR" == "dependabot[bot]" || "$AUTHOR" == "gtrack-sync-bot" ]]; then
            TRUSTED=true
          fi
          echo "trusted=$TRUSTED" >> $GITHUB_OUTPUT
          echo "ref=$REF labels=$LABELS title=$TITLE author=$AUTHOR trusted=$TRUSTED"

      - name: Enable auto-merge (squash)
        if: steps.files.outputs.in_import == 'true' && steps.trust.outputs.trusted == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          echo "Enabling --auto squash merge for PR #$PR"
          gh pr merge "$PR" --squash --auto
