name: Docs Healthcheck

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  pull_request:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check docs portal availability
        run: |
          curl --fail --silent --show-error --location --retry 3 --retry-all-errors https://docs.g-track.eu > /dev/null
