name: Docs - Preview

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-preview.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs
        if: hashFiles('mkdocs.yml') != ''
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Build documentation
        if: hashFiles('mkdocs.yml') != ''
        run: mkdocs build --strict
