name: Docs – Sync Repos
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Source refs (default: default branch)"
        required: false
  schedule:
    - cron: "17 6 * * 1"   # weekly Monday 06:17 UTC

permissions:
  contents: write
  pull-requests: write

env:
  SYNC_REPOS_TOKEN: ${{ secrets.SYNC_REPOS_TOKEN }}
  GIT_AUTHOR_NAME:  gtrack-bot
  GIT_AUTHOR_EMAIL: bot@users.noreply.github.com
  GIT_COMMITTER_NAME:  gtrack-bot
  GIT_COMMITTER_EMAIL: bot@users.noreply.github.com

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout docs
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: tqlismqn/gtrack-backend
          token: ${{ env.SYNC_REPOS_TOKEN }}
          path: _src/backend
          ref: ${{ inputs.ref || '' }}

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: tqlismqn/gtrack-frontend
          token: ${{ env.SYNC_REPOS_TOKEN }}
          path: _src/frontend
          ref: ${{ inputs.ref || '' }}

      - name: Sync files (README + docs/* if present)
        id: sync
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p docs/import/backend docs/import/frontend
          # Backend
          if [ -f _src/backend/README.md ]; then
            cp _src/backend/README.md docs/import/backend/README.md
          fi
          if [ -d _src/backend/docs ]; then
            # Backend docs → preserve local notes
            rsync -a --delete \
              --exclude='_notes/**' \
              --prune-empty-dirs --include='*/' --include='*.md' --include='*.yaml' --exclude='*' \
              _src/backend/docs/ docs/import/backend/
          fi
          # Frontend
          if [ -f _src/frontend/README.md ]; then
            cp _src/frontend/README.md docs/import/frontend/README.md
          fi
          if [ -d _src/frontend/docs ]; then
            # Frontend docs → preserve local notes
            rsync -a --delete \
              --exclude='_notes/**' \
              --prune-empty-dirs --include='*/' --include='*.md' --include='*.yaml' --exclude='*' \
              _src/frontend/docs/ docs/import/frontend/
          fi

          # Nothing to commit?
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to sync."
            exit 0
          fi

          git add -A
          git commit -m "docs(sync): import from gtrack-backend & gtrack-frontend"
          echo "changes=true" >> $GITHUB_OUTPUT

      - name: Push branch & open PR
        if: steps.sync.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "docs(sync): import from gtrack-backend & gtrack-frontend"
          body: |
            Automated sync of README and docs/** from backend & frontend.
          branch: "ci/docs-auto-sync"
          labels: "docs,sync"
