name: Docs – Auto Merge Sync PRs
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, ready_for_review]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  guard-and-merge:
    if: >
      github.event.pull_request != null &&
      contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base (docs)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
          submodules: false

      - name: Paths filter (only allow docs/import/**)
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            only-import:
              - 'docs/import/**'
            everything-else:
              - '**'
              - '!docs/import/**'

      - name: Stop if changes outside import/
        if: steps.changes.outputs['everything-else'] == 'true'
        run: |
          echo "::warning::Found changes outside docs/import/**. Auto-merge aborted."
          exit 0

      # Если включено требование ревью — автоапрувим PR с меткой automerge
      - name: Auto-approve (when approvals required)
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Включаем автоматическое слияние как только все чеки зелёные и ветка up-to-date
      - name: Auto-merge
        uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          delete-branch: true
          require-all-status-checks: true
          # Доп. условия безопасности:
          allowed-author: ${{ github.repository_owner }}
          # разрешим также PR от github-actions (если auto-sync создаёт PR от бота)
          allow-bots: true
