name: Docs – Auto Sync to Import
on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"   # daily at 03:17 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      OWNER: tqlismqn
      FE_REPO: tqlismqn/gtrack-app
      BE_REPO: tqlismqn/gtrack-backend
      PR_BRANCH_PREFIX: sync
    steps:
      # Checkout this docs repo (target)
      - name: Checkout gtrack-docs
        uses: actions/checkout@v4

      # Guard: secret must exist
      - name: Check secret
        run: |
          if [ -z "${{ secrets.SYNC_REPOS_TOKEN }}" ]; then
            echo "::error::Secret SYNC_REPOS_TOKEN is missing in $GITHUB_REPOSITORY"; exit 1;
          fi

      # Checkout FE docs
      - name: Checkout gtrack-app (docs)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.FE_REPO }}
          ref: main
          path: fe
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          fetch-depth: 1

      # Checkout BE docs
      - name: Checkout gtrack-backend (docs)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BE_REPO }}
          ref: main
          path: be
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          fetch-depth: 1

      # Prepare import tree
      - name: Copy FE/BE docs into import/
        run: |
          mkdir -p docs/import/frontend/gtrack-app docs/import/backend/gtrack-backend
          rsync -a --delete fe/docs/ docs/import/frontend/gtrack-app/ || true
          rsync -a --delete be/docs/ docs/import/backend/gtrack-backend/ || true
          echo "Changed files:"; git status --porcelain

      # Create PR to this repo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          commit-message: "docs(sync): import from gtrack-app & gtrack-backend"
          title: "docs(sync): import from gtrack-app & gtrack-backend"
          body: |
            Auto-sync from `${{ env.FE_REPO }}` and `${{ env.BE_REPO }}`.
            Source branches: main.
          branch: ${{ env.PR_BRANCH_PREFIX }}/combined
          branch-suffix: timestamp
          delete-branch: true
