name: docs-auto-merge-sync

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, ready_for_review]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-and-merge:
    name: Enable auto-merge for sync PRs (CLI)
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "PR=${{ github.event.pull_request.number }}"
          echo "ref=${{ github.event.pull_request.head.ref }}"
          echo "title=${{ github.event.pull_request.title }}"
          echo "author=${{ github.event.pull_request.user.login }}"
          echo "labels=$(echo "${{ join(github.event.pull_request.labels.*.name, ',') }}")"

      - name: Collect changed files (docs-only)
        id: files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          FILES=$(gh api "repos/${{ github.repository }}/pulls/$PR/files" --paginate --jq '.[].filename')
          echo "Changed files:"; echo "$FILES"
          ALL_IN_DOCS=true
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            if [[ "$f" != docs/* ]]; then ALL_IN_DOCS=false; fi
          done <<< "$FILES"
          if ! $ALL_IN_DOCS; then
            echo "::notice::PR touches files outside docs/**. Skipping auto-merge."
            echo "docs_only=false" >> $GITHUB_OUTPUT
          else
            echo "docs_only=true" >> $GITHUB_OUTPUT
          fi

      - name: Decide trust
        id: trust
        run: |
          REF="${{ github.event.pull_request.head.ref }}"
          TITLE="${{ github.event.pull_request.title }}"
          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          TRUSTED=false
          if [[ "$REF" == *sync* || "$LABELS" == *sync* || "$TITLE" == *"docs(sync)"* || "$AUTHOR" == "tqlismqn" || "$AUTHOR" == "dependabot[bot]" || "$AUTHOR" == "gtrack-sync-bot" ]]; then
            TRUSTED=true
          fi
          echo "trusted=$TRUSTED" >> $GITHUB_OUTPUT

      - name: Enable auto-merge (squash)
        if: steps.files.outputs.docs_only == 'true' && steps.trust.outputs.trusted == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          PR=${{ github.event.pull_request.number }}
          echo "Enabling --auto squash merge for PR #$PR"
          gh pr merge "$PR" --squash --auto || {
            echo "Retry once in 5s…"
            sleep 5
            gh pr merge "$PR" --squash --auto || true
          }
