name: Docs – Auto Sync to Import
on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"
  repository_dispatch:
    types: [sync-import]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FE_REPO: tqlismqn/gtrack-app
      BE_REPO: tqlismqn/gtrack-backend
      PR_BRANCH_PREFIX: sync
    steps:
      - name: Checkout gtrack-docs
        uses: actions/checkout@v4

      - name: Guard secret
        run: |
          [ -n "${{ secrets.SYNC_REPOS_TOKEN }}" ] || { echo "::error::Secret SYNC_REPOS_TOKEN missing"; exit 1; }

      - name: Checkout gtrack-app (docs)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.FE_REPO }}
          ref: main
          path: fe
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          fetch-depth: 1

      - name: Checkout gtrack-backend (docs)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.BE_REPO }}
          ref: main
          path: be
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          fetch-depth: 1

      - name: Copy into import tree
        run: |
          mkdir -p docs/import/frontend/gtrack-app docs/import/backend/gtrack-backend
          rsync -a --delete fe/docs/ docs/import/frontend/gtrack-app/ || true
          rsync -a --delete be/docs/ docs/import/backend/gtrack-backend/ || true

      - name: Write meta SHAs (guarantee diff on any upstream change)
        run: |
          mkdir -p docs/import/_meta/frontend docs/import/_meta/backend
          git -C fe rev-parse HEAD > docs/import/_meta/frontend/gtrack-app.sha
          git -C be rev-parse HEAD > docs/import/_meta/backend/gtrack-backend.sha

      - name: Generate simple indexes
        run: |
          gen_idx () {
            d="$1"; t="$2"; mkdir -p "$d"
            {
              echo "# ${t} — импортированные файлы"
              echo
              shopt -s nullglob
              for f in "$d"/*.md; do
                bn=$(basename "$f")
                [ "$bn" = "index.md" ] && continue
                echo "- [${bn}](${bn})"
              done
            } > "$d/index.md"
          }
          gen_idx docs/import/frontend/gtrack-app "gtrack-app"
          gen_idx docs/import/backend/gtrack-backend "gtrack-backend"
      - name: Cleanup temp repos
        run: |
          rm -rf fe be || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SYNC_REPOS_TOKEN }}
          commit-message: "docs(sync): import from gtrack-app & gtrack-backend"
          title: "docs(sync): import FE/BE docs"
          body: "Auto-sync from `${{ env.FE_REPO }}` and `${{ env.BE_REPO }}`."
          branch: ${{ env.PR_BRANCH_PREFIX }}/combined
          branch-suffix: timestamp
          labels: docs,sync,automerge
          delete-branch: true
