name: Docs - Preview & Build
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - name: Build mkdocs
        run: mkdocs build --strict
