name: docs-auto-merge-sync

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review, edited, review_requested]
    branches: [main]
    paths:
      - 'docs/import/**'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: automerge-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  enable-and-merge:
    name: Enable auto-merge for sync PRs
    if: >
      startsWith(github.head_ref, 'sync') ||
      contains(github.head_ref, 'sync') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'sync') ||
      contains(github.event.pull_request.title, 'docs(sync)') ||
      contains('tqlismqn,dependabot[bot],gtrack-sync-bot', github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "head_ref=${{ github.head_ref }}"
          echo "title=${{ github.event.pull_request.title }}"
          echo "author=${{ github.event.pull_request.user.login }}"
          echo "labels=$(echo "${{ toJson(github.event.pull_request.labels) }}" | tr -d '\n')"

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Auto-merge when checks pass
        uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
